version: "3.9"
services:
  web:
    image: node:16-alpine
    environment:
      REDIS_HOST: "redis://redis:6379"
      HTTP_ADDR: "0.0.0.0"
      NOSSL_PORT: "8080"
    volumes:
      - .:/app
      - ./config.js.template:/app/config.js
      - node_modules:/app/node_modules
    working_dir: /app
    command: npm start
    ports:
      - 8080:8080
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
volumes:
  node_modules:
